CREATE TABLE patients (
	patientId INTEGER PRIMARY KEY AUTOINCREMENT,
	name TEXT,
	lastname TEXT,
	age INTEGER,
	insurance TEXT,
	doctor TEXT,
	other TEXT,
	dateCreated DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	lastUpdated DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE reports (
	reportId INTEGER PRIMARY KEY AUTOINCREMENT,
	patientId INTEGER NOT NULL,
	exploration TEXT,
	body TEXT,
	dateCreated DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	lastUpdated DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY(patientId) REFERENCES patients(patientId)
);

CREATE TABLE images (
	imageId INTEGER PRIMARY KEY AUTOINCREMENT,
	reportId INTEGER NOT NULL,
	rawData BLOB,
	dateCreated DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	lastUpdated DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY(reportId) REFERENCES reports(reportId)
);